import { CATEGORIES } from './navbar.type';
import { Product, PRODUCT_TYPE } from './products.type';

export const productsData: Product[] = [
  {
    image: 'assets/item5.png',
    title: 'تيشيرت-كم طويل-آرت وير-نسائي',
    category: CATEGORIES.womensSection,
    rate: 1,
    sale: 90,
    price: 150,
    currency: 'ج.م',
    new: false,
    type: PRODUCT_TYPE.new,
  },
  {
    image: 'assets/item3.png',
    title: 'تيشيرت-كم طويل-آرت وير-نسائي',
    category: CATEGORIES.menSection,
    rate: 2,
    price: 90,
    currency: 'ج.م',
    new: true,
    type: PRODUCT_TYPE.new,
  },
  {
    image: 'assets/item1.png',
    title: 'تيشيرت-كم طويل-آرت وير-نسائي',
    category: CATEGORIES.mobilesSection,
    rate: 4,
    price: 90,
    currency: 'ج.م',
    new: true,
    type: PRODUCT_TYPE.new,
  },
  {
    image: 'assets/item2.png',
    title: 'تيشيرت-كم طويل-آرت وير-نسائي',
    category: CATEGORIES.mobilesSection,
    rate: 5,
    price: 90,
    currency: 'ج.م',
    new: true,
    type: PRODUCT_TYPE.new,
  },
  {
    image: 'assets/item6.png',
    title: 'تيشيرت-كم طويل-آرت وير-نسائي',
    category: CATEGORIES.womensSection,
    rate: 1,
    sale: 100,
    price: 140,
    currency: 'ج.م',
    new: true,
    type: PRODUCT_TYPE.recentlyViewed,
  },
  {
    image: 'assets/item4.png',
    title: 'تيشيرت-كم طويل-آرت وير-نسائي',
    category: CATEGORIES.accessoriesSection,
    rate: 4,
    price: 150,
    currency: 'ج.م',
    new: false,
    type: PRODUCT_TYPE.recentlyViewed,
  },
  {
    image: 'assets/item7.png',
    title: 'تيشيرت-كم طويل-آرت وير-نسائي',
    category: CATEGORIES.womensSection,
    rate: 3,
    sale: 90,
    price: 150,
    currency: 'ج.م',
    new: false,
    type: PRODUCT_TYPE.recentlyViewed,
  },
];
